### ISSUE TITLE
Tox command fails with 'ValueError: No closing quotation'

### ISSUE THREAD

**Issue by kdelwat** [audreyr/cookiecutter-pypackage#286]
* Date you used Cookiecutter PyPackage: 22/12/16
* Cookiecutter version used, if any: 1.5.0
* Python version, if any: 3.5.2
* Operating System: Arch Linux

### Description

After following the instructions in the tutorial, and modifying the list of Tox environments (`envlist`), running the `tox` command fails.

## Input
```
tox
```

## Output
```
Traceback (most recent call last):
  File "/home/cadel/.venvs/messengerplatform/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/home/cadel/.venvs/messengerplatform/lib/python3.5/site-packages/tox/session.py", line 38, in main
    config = prepare(args)
  File "/home/cadel/.venvs/messengerplatform/lib/python3.5/site-packages/tox/session.py", line 26, in prepare
    config = parseconfig(args)
  File "/home/cadel/.venvs/messengerplatform/lib/python3.5/site-packages/tox/config.py", line 229, in parseconfig
    parseini(config, inipath)
  File "/home/cadel/.venvs/messengerplatform/lib/python3.5/site-packages/tox/config.py", line 729, in __init__
    self.make_envconfig(name, section, reader._subs, config)
  File "/home/cadel/.venvs/messengerplatform/lib/python3.5/site-packages/tox/config.py", line 760, in make_envconfig
    res = meth(env_attr.name, env_attr.default)
  File "/home/cadel/.venvs/messengerplatform/lib/python3.5/site-packages/tox/config.py", line 929, in getargvlist
    return _ArgvlistReader.getargvlist(self, s)
  File "/home/cadel/.venvs/messengerplatform/lib/python3.5/site-packages/tox/config.py", line 1100, in getargvlist
    commands.append(cls.processcommand(reader, current_command))
  File "/home/cadel/.venvs/messengerplatform/lib/python3.5/site-packages/tox/config.py", line 1140, in processcommand
    argv = list(shlexer)
  File "/usr/lib64/python3.5/shlex.py", line 263, in __next__
    token = self.get_token()
  File "/usr/lib64/python3.5/shlex.py", line 90, in get_token
    raw = self.read_token()
  File "/usr/lib64/python3.5/shlex.py", line 166, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
```

The tox config file is as follows:

```
[tox]
envlist = py35, flake8

[testenv:flake8]
basepython=python
deps=flake8
commands=flake8 messengerplatform

[testenv]
setenv =
    PYTHONPATH = {toxinidir}:{toxinidir}/messengerplatform
deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    pip install -U pip
    py.test --basetemp={envtmpdir}


; If you want to make tox run the tests with the same versions, create a
; requirements.txt with the pinned versions and uncomment the following lines:
; deps =
;     -r{toxinidir}/requirements.txt
```

**Comment by obestwalter** [comment]
Hi @kdelwat,

I just started playing around with cookiecutter and created a fresh project from this template with cookiecutter 1.5.1 - everything works as expected. Tox tests are green for all environments. I am also on arch linux. I guess you must trigger some corner case. I am pretty sure that this has to with the path your project is is in.

Could you run this again with tox in verbose mode (`tox -vv`)?

Try if this problem persists if you move your project e.g. directly into your home folder.

**Comment by kdelwat** [comment]
@obestwalter, thanks for the reply.

After testing the same environment with the latest versions of Tox and Python (3.6), I no longer experience the issue. I assume it was an upstream problem in Tox!
