### ISSUE TITLE
Travis PyPi deploy fails

### ISSUE THREAD

**Issue by miohtama** [audreyr/cookiecutter-pypackage#95]
I got this failure through properly set up .travis.yml deploy hook today. The package somehow tries to install itself (which do not exist yet?) for sdist.

    Installed /home/travis/build/websauna/pyramid_sms/.eggs/pytest_runner-2.7.1-py3.4.egg

    fatal: No names found, cannot describe anything.

    Traceback (most recent call last):

      File "/home/travis/build/websauna/pyramid_sms/.eggs/setuptools_git_version-1.0.3-py3.4.egg/setuptools_git_version.py", line 10, in validate_version_format

      File "/opt/python/3.4.2/lib/python3.4/subprocess.py", line 620, in check_output

        raise CalledProcessError(retcode, process.args, output=output)

    subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):

      File "setup.py", line 65, in <module>

        'twilio': ["twilio"],

      File "/opt/python/3.4.2/lib/python3.4/distutils/core.py", line 108, in setup

        _setup_distribution = dist = klass(attrs)

      File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/setuptools/dist.py", line 269, in __init__

        _Distribution.__init__(self,attrs)

      File "/opt/python/3.4.2/lib/python3.4/distutils/dist.py", line 280, in __init__

        self.finalize_options()

      File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/setuptools/dist.py", line 325, in finalize_options

        ep.load()(self, ep.name, value)

      File "/home/travis/build/websauna/pyramid_sms/.eggs/setuptools_git_version-1.0.3-py3.4.egg/setuptools_git_version.py", line 12, in validate_version_format

      File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pkg_resources/__init__.py", line 512, in get_distribution

        dist = get_provider(dist)

      File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pkg_resources/__init__.py", line 392, in get_provider

        return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]

      File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pkg_resources/__init__.py", line 918, in require

        needed = self.resolve(parse_requirements(requirements))

      File "/home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/pkg_resources/__init__.py", line 805, in resolve

        raise DistributionNotFound(req)

    pkg_resources.DistributionNotFound: pyramid-sms

    ERROR: FAIL could not package project - v = InvocationError('/home/travis/virtualenv/python3.4.2/bin/python /home/travis/build/websauna/pyramid_sms/setup.py sdist --formats=zip --dist-dir /home/travis/build/websauna/pyramid_sms/.tox/dist (see /home/travis/build/websauna/pyramid_sms/.tox/log/tox-0.log)', 1)

    The command "tox" exited with 2.

    Done. Your build exited with 1.

**Comment by miohtama** [comment]
Invalid report. It was a problem with setup.py.
